//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thebigfour.SvcRefBoxWear {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefBoxWear.IWsBoxWear")]
    public interface IWsBoxWear {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBoxWear/GetPOList", ReplyAction="http://tempuri.org/IWsBoxWear/GetPOListResponse")]
        System.Data.DataSet GetPOList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsBoxWear/GetPOList", ReplyAction="http://tempuri.org/IWsBoxWear/GetPOListResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPOListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsBoxWearChannel : thebigfour.SvcRefBoxWear.IWsBoxWear, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsBoxWearClient : System.ServiceModel.ClientBase<thebigfour.SvcRefBoxWear.IWsBoxWear>, thebigfour.SvcRefBoxWear.IWsBoxWear {
        
        public WsBoxWearClient() {
        }
        
        public WsBoxWearClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsBoxWearClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBoxWearClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsBoxWearClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPOList() {
            return base.Channel.GetPOList();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPOListAsync() {
            return base.Channel.GetPOListAsync();
        }
    }
}
