//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thebigfour.SvcRefJudoVan {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefJudoVan.IWsJudoVan")]
    public interface IWsJudoVan {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsJudoVan/getDeliveryStatus", ReplyAction="http://tempuri.org/IWsJudoVan/getDeliveryStatusResponse")]
        System.Data.DataSet getDeliveryStatus(int trackingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsJudoVan/getDeliveryStatus", ReplyAction="http://tempuri.org/IWsJudoVan/getDeliveryStatusResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getDeliveryStatusAsync(int trackingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsJudoVan/createDelivery", ReplyAction="http://tempuri.org/IWsJudoVan/createDeliveryResponse")]
        int createDelivery(decimal weight, string deliveryStatus, int PoID, int invoiceID, string dateRegistered, string deliveryType, string ProductDesc, int ProductQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsJudoVan/createDelivery", ReplyAction="http://tempuri.org/IWsJudoVan/createDeliveryResponse")]
        System.Threading.Tasks.Task<int> createDeliveryAsync(decimal weight, string deliveryStatus, int PoID, int invoiceID, string dateRegistered, string deliveryType, string ProductDesc, int ProductQty);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsJudoVanChannel : thebigfour.SvcRefJudoVan.IWsJudoVan, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsJudoVanClient : System.ServiceModel.ClientBase<thebigfour.SvcRefJudoVan.IWsJudoVan>, thebigfour.SvcRefJudoVan.IWsJudoVan {
        
        public WsJudoVanClient() {
        }
        
        public WsJudoVanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsJudoVanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsJudoVanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsJudoVanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getDeliveryStatus(int trackingID) {
            return base.Channel.getDeliveryStatus(trackingID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getDeliveryStatusAsync(int trackingID) {
            return base.Channel.getDeliveryStatusAsync(trackingID);
        }
        
        public int createDelivery(decimal weight, string deliveryStatus, int PoID, int invoiceID, string dateRegistered, string deliveryType, string ProductDesc, int ProductQty) {
            return base.Channel.createDelivery(weight, deliveryStatus, PoID, invoiceID, dateRegistered, deliveryType, ProductDesc, ProductQty);
        }
        
        public System.Threading.Tasks.Task<int> createDeliveryAsync(decimal weight, string deliveryStatus, int PoID, int invoiceID, string dateRegistered, string deliveryType, string ProductDesc, int ProductQty) {
            return base.Channel.createDeliveryAsync(weight, deliveryStatus, PoID, invoiceID, dateRegistered, deliveryType, ProductDesc, ProductQty);
        }
    }
}
