//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boxwear.SvcRefTheBigFour {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefTheBigFour.IWsTheBigFour")]
    public interface IWsTheBigFour {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTheBigFour/GetAllPurchaseOrder", ReplyAction="http://tempuri.org/IWsTheBigFour/GetAllPurchaseOrderResponse")]
        System.Data.DataSet GetAllPurchaseOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTheBigFour/GetAllPurchaseOrder", ReplyAction="http://tempuri.org/IWsTheBigFour/GetAllPurchaseOrderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllPurchaseOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTheBigFour/GetAllProducts", ReplyAction="http://tempuri.org/IWsTheBigFour/GetAllProductsResponse")]
        System.Data.DataSet GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTheBigFour/GetAllProducts", ReplyAction="http://tempuri.org/IWsTheBigFour/GetAllProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTheBigFour/GetProductImage", ReplyAction="http://tempuri.org/IWsTheBigFour/GetProductImageResponse")]
        System.Data.DataSet GetProductImage(int prodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsTheBigFour/GetProductImage", ReplyAction="http://tempuri.org/IWsTheBigFour/GetProductImageResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductImageAsync(int prodID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsTheBigFourChannel : boxwear.SvcRefTheBigFour.IWsTheBigFour, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsTheBigFourClient : System.ServiceModel.ClientBase<boxwear.SvcRefTheBigFour.IWsTheBigFour>, boxwear.SvcRefTheBigFour.IWsTheBigFour {
        
        public WsTheBigFourClient() {
        }
        
        public WsTheBigFourClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsTheBigFourClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTheBigFourClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTheBigFourClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllPurchaseOrder() {
            return base.Channel.GetAllPurchaseOrder();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllPurchaseOrderAsync() {
            return base.Channel.GetAllPurchaseOrderAsync();
        }
        
        public System.Data.DataSet GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public System.Data.DataSet GetProductImage(int prodID) {
            return base.Channel.GetProductImage(prodID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductImageAsync(int prodID) {
            return base.Channel.GetProductImageAsync(prodID);
        }
    }
}
